### ISSUE TITLE
Can't add package via SPM on Xcode 15.4

### ISSUE THREAD

**Issue by DimDL** [GeoEdgeSDK/AppHarbrSDK#1]
Config
- Xcode 15.4
- added in my module's package.swift dependencies:
`.package(url: "https://github.com/GeoEdgeSDK/AppHarbrSDK", exact: "1.14.3")`

Xcode error: 
`Source files for target AppHarbrSDK should be located under 'Sources/AppHarbrSDK', or a custom sources path can be set with the 'path' property in Package.swift`

**Comment by GeoEdgeSDK** [comment]
Hi @DimDL,

We are unable to reproduce this issue on our end. To help us investigate further, could you please provide more details about your project setup or a minimal setup to reproduce the issue?

Thank you!

**Comment by DimDL** [comment]
Hi @GeoEdgeSDK,
Good news : can't repro it either; tried on sample app + our main ap, both adding to .xcodeproj and Package.swift file. 
So OK to close, sorry for the noise, must have been an SPM transient issue.
